name: main

on: [push, pull_request]

env:
  NODE_VERSION: 14.x

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test on ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install modules
        run: yarn
      - name: Run the typescript compiler
        run: yarn tsc
      - name: Run the linter
        run: yarn lint
      - name: Run tests
        run: yarn test
