name: Playwright Tests
on: [deployment_status]
jobs:
  test:
    if: github.event.deployment_status.state == 'success'
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install
      - name: Install Playwright Browsers
        run: bunx playwright install --with-deps
      - name: Will test against ${{ github.event.deployment_status.target_url }}
        run: echo NEXT_PUBLIC_ROOT_URL ${{ github.event.deployment_status.target_url }}
      - name: Run Playwright tests
        run: bun run test:e2e
        env:
          NEXT_PUBLIC_ROOT_URL: ${{ github.event.deployment_status.target_url }}
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
